default_config:
    
homeassistant:
    name: your-unit-name
    latitude: your-latitude
    longitude: your-longitude
    elevation: your-elevation
    unit_system: metric
    currency: CLP
    time_zone: "America/Santiago"
    external_url: ""
    internal_url: "http://homeassistant.local:8123"
    allowlist_external_dirs:
    #- "/usr/var/dumping-ground"
    #- "/tmp"
    allowlist_external_urls:
    media_dirs:
    media: "/media"
    recordings: "/mnt/recordings"
    legacy_templates: false

python_script:
    requirements:

#group: !include groups.yaml
#scene: !include scenes.yaml
#script: !include scripts.yaml 
camera: !include cameras.yaml
#counter: !include counters.yaml
#automation: !include automations.yaml
#image_processing: !include image_processings.yaml